const colors = {
  light: {
    text: "#1D1B19",
    tint: "#154212",
    background: "#FFF8F4",
    foreground: "#1D1B19",
    surface: "#FFF8F4",
    surfaceContainer: "#F3EDE8",
    surfaceContainerLow: "#F9F2EE",
    surfaceContainerHigh: "#EDE7E3",
    card: "#FFFFFF",
    cardForeground: "#1D1B19",
    primary: "#154212",
    primaryContainer: "#2D5A27",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#9DD090",
    primaryForeground: "#FFFFFF",
    secondary: "#8B500A",
    secondaryContainer: "#FFB065",
    onSecondary: "#FFFFFF",
    secondaryForeground: "#FFFFFF",
    tertiary: "#493700",
    tertiaryFixed: "#FFDF96",
    tertiaryContainer: "#654D00",
    onTertiaryContainer: "#E3BF65",
    onSurface: "#1D1B19",
    onSurfaceVariant: "#45483F",
    muted: "#F3EDE8",
    mutedForeground: "#767D6C",
    accent: "#FFDF96",
    accentForeground: "#493700",
    destructive: "#BA1A1A",
    destructiveForeground: "#FFFFFF",
    border: "#C2C9BB",
    input: "#EDE7E3",
    outline: "#767D6C",
    outlineVariant: "#C2C9BB",
    tabBarActive: "#154212",
    tabBarInactive: "#767D6C",
    tabBarBackground: "#FFF8F4",
  },
  radius: 16,
};

export default colors;
