import type { Condition, DayMenu, Meal } from "./types";

export const CONDITIONS: {
  id: Condition;
  label: string;
  description: string;
  icon: string;
  color: string;
}[] = [
  {
    id: "hypertension",
    label: "Hypertension",
    description: "Low sodium focus with potassium-rich traditional ingredients",
    icon: "heart",
    color: "#BA1A1A",
  },
  {
    id: "diabetes",
    label: "Diabetes",
    description: "Glycemic control using ancient grains like Fonio and Guinea Corn",
    icon: "activity",
    color: "#2D5A27",
  },
  {
    id: "weightloss",
    label: "Weight Loss",
    description: "Satiety-focused, high-fiber and portion-controlled",
    icon: "trending-down",
    color: "#493700",
  },
  {
    id: "liver",
    label: "Liver Health",
    description: "Detoxifying meal plans highlighting bitter greens and turmeric",
    icon: "shield",
    color: "#8B500A",
  },
  {
    id: "allergies",
    label: "Allergies",
    description: "Exclude common triggers like shellfish, nuts or specific legumes",
    icon: "alert-triangle",
    color: "#767D6C",
  },
];

export const DIETARY_RESTRICTIONS = [
  "Gluten-Free",
  "Dairy-Free",
  "Nut-Free",
  "No Shellfish",
  "Vegetarian",
  "No Pork",
  "Low FODMAPs",
];

export const TAG_COLORS: Record<string, { bg: string; text: string }> = {
  "Low Sodium": { bg: "#E8F5E9", text: "#2D5A27" },
  "Heart Healthy": { bg: "#FFEBEE", text: "#BA1A1A" },
  "Diabetic-Friendly": { bg: "#E8F5E9", text: "#154212" },
  "High Fiber": { bg: "#FFF8E1", text: "#493700" },
  "Anti-Inflammatory": { bg: "#E8EAF6", text: "#283593" },
  "Protein Rich": { bg: "#F3E5F5", text: "#6A1B9A" },
  "Low Calorie": { bg: "#E0F7FA", text: "#006064" },
  Keto: { bg: "#F1F8E9", text: "#558B2F" },
  "Gluten-Free": { bg: "#FFF3E0", text: "#E65100" },
  Detox: { bg: "#E8F5E9", text: "#2D5A27" },
  Antioxidant: { bg: "#FCE4EC", text: "#880E4F" },
  "Immune Boost": { bg: "#E3F2FD", text: "#0D47A1" },
  "Iron Rich": { bg: "#EFEBE9", text: "#4E342E" },
  Probiotic: { bg: "#E8EAF6", text: "#3949AB" },
  "Energy Boost": { bg: "#FFFDE7", text: "#F57F17" },
};

export const DELIVERY_FEE = 1200;

const WEEKLY_MENU: DayMenu[] = [
  {
    day: "Monday",
    theme: "Eastern Nigerian Delights",
    themeDescription:
      "Healing flavors from the heart of the East, crafted for your metabolic vitality.",
    meals: [
      {
        id: "mon-b1",
        name: "Akara & Herb Jus",
        description:
          "Whipped bean fritters infused with ginger and turmeric, served with aromatic herb jus",
        price: 2800,
        calories: 320,
        protein: 18,
        carbs: 35,
        fat: 12,
        fiber: 8,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Low Sodium", "Protein Rich", "Heart Healthy"],
        conditions: ["hypertension", "weightloss"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Organic Black-eyed Beans",
          "Fresh Ginger",
          "Turmeric",
          "Scent Leaves",
        ],
        healthImpact:
          "High in plant protein and potassium, supporting healthy blood pressure and sustained energy release.",
        chefNote:
          "Our beans are soaked for 12 hours in filtered water to maximise nutrient availability.",
      },
      {
        id: "mon-l1",
        name: "Native Ugu Fusion",
        description:
          "Double-tested pumpkin leaves woven with omega-enriched stock",
        price: 4500,
        calories: 380,
        protein: 22,
        carbs: 42,
        fat: 14,
        fiber: 12,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Diabetic-Friendly", "High Fiber", "Anti-Inflammatory"],
        conditions: ["diabetes", "liver", "hypertension"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Organic Ugu Leaves",
          "Crayfish",
          "Palm Oil (cold-pressed)",
          "Periwinkle",
        ],
        healthImpact:
          "Rich in iron, folate and antioxidants. Supports glycaemic control and liver detoxification.",
      },
      {
        id: "mon-d1",
        name: "Smoked Croaker & Yam",
        description:
          "Slow-roasted wild fish with fine-grilled purple yam wedges",
        price: 6200,
        calories: 520,
        protein: 38,
        carbs: 48,
        fat: 18,
        fiber: 9,
        glycemicIndex: "Medium",
        sodiumLevel: "Medium",
        tags: ["Heart Healthy", "Gluten-Free", "Protein Rich"],
        conditions: ["weightloss", "hypertension"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: [
          "Wild-caught Croaker",
          "Purple Yam",
          "Uziza Leaves",
          "Cold-pressed Palm Oil",
        ],
        healthImpact:
          "Omega-3 rich fish promotes heart health while purple yam provides resistant starch for gut health.",
      },
      {
        id: "mon-dr1",
        name: "Zobo Hibiscus Tonic",
        description:
          "Fermented hibiscus flowers with ginger and clove, rich in antioxidants",
        price: 1800,
        calories: 45,
        protein: 0,
        carbs: 11,
        fat: 0,
        fiber: 1,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Antioxidant", "Heart Healthy", "Anti-Inflammatory"],
        conditions: ["hypertension", "diabetes", "liver"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Dried Hibiscus", "Fresh Ginger", "Clove", "Lemon"],
        healthImpact:
          "Naturally lowers blood pressure and packed with vitamin C.",
      },
      {
        id: "mon-dr2",
        name: "Ginger-Turmeric Brew",
        description: "Cold-pressed, unsweetened",
        price: 1500,
        calories: 35,
        protein: 1,
        carbs: 8,
        fat: 0,
        fiber: 1,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Anti-Inflammatory", "Detox", "Immune Boost"],
        conditions: ["liver", "diabetes", "hypertension"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: [
          "Fresh Turmeric",
          "Ginger Root",
          "Black Pepper",
          "Lemon",
        ],
        healthImpact:
          "Curcumin in turmeric reduces inflammation and supports liver detoxification.",
      },
    ],
  },
  {
    day: "Tuesday",
    theme: "Northern Nigerian Flavors",
    themeDescription:
      "Ancient grains and heritage spices from the Sahel, nourishing body and spirit.",
    meals: [
      {
        id: "tue-b1",
        name: "Morning Millet Porridge",
        description:
          "Slow-cooked fonio and millet with honey and baobab powder",
        price: 2200,
        calories: 280,
        protein: 10,
        carbs: 52,
        fat: 4,
        fiber: 9,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Low Glycemic", "High Fiber", "Energy Boost"],
        conditions: ["diabetes", "weightloss"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Fonio",
          "Pearl Millet",
          "Baobab Powder",
          "Raw Honey",
        ],
        healthImpact:
          "Ancient grains provide sustained energy with minimal blood sugar spike.",
      },
      {
        id: "tue-l1",
        name: "Groundnut Soup & Grain",
        description:
          "Traditional groundnut stew with roasted peanuts, served over guinea corn",
        price: 4800,
        calories: 460,
        protein: 28,
        carbs: 50,
        fat: 20,
        fiber: 11,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Protein Rich", "High Fiber", "Low Sodium"],
        conditions: ["hypertension", "weightloss"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Heritage Groundnuts",
          "Guinea Corn",
          "Dry Fish",
          "Traditional Spices",
        ],
        healthImpact:
          "High in monounsaturated fats that support cardiovascular health and brain function.",
      },
      {
        id: "tue-d1",
        name: "Tuwo & Miyan Kuka",
        description: "Silky rice pudding with baobab leaf soup and dried fish",
        price: 5500,
        calories: 490,
        protein: 25,
        carbs: 65,
        fat: 12,
        fiber: 8,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Detox", "Anti-Inflammatory", "Protein Rich"],
        conditions: ["liver", "hypertension"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: [
          "Heritage Rice",
          "Baobab Leaves",
          "Potash",
          "Dried Fish",
        ],
        healthImpact:
          "Baobab leaves are exceptionally rich in calcium and iron, supporting bone health.",
      },
      {
        id: "tue-dr1",
        name: "Tamarind Wellness Shot",
        description: "Concentrated tamarind with pepper and ginger",
        price: 1600,
        calories: 40,
        protein: 0,
        carbs: 10,
        fat: 0,
        fiber: 2,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Digestive Aid", "Antioxidant"],
        conditions: ["liver", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Tamarind", "Ginger", "Black Pepper", "Honey"],
        healthImpact:
          "Supports digestion and has natural laxative properties for gut health.",
      },
      {
        id: "tue-dr2",
        name: "Baobab Immunity Blend",
        description: "6x Vitamin C of oranges, unsweetened",
        price: 1700,
        calories: 50,
        protein: 1,
        carbs: 12,
        fat: 0,
        fiber: 3,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Immune Boost", "Antioxidant", "Energy Boost"],
        conditions: ["liver", "weightloss"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Baobab Powder", "Water", "Lemon", "Mint"],
        healthImpact:
          "Baobab contains more Vitamin C than most citrus fruits, boosting immunity significantly.",
      },
    ],
  },
  {
    day: "Wednesday",
    theme: "Western Nigerian Cuisine",
    themeDescription:
      "Bold Yoruba flavors and heritage vegetables, optimised for modern metabolic wellness.",
    meals: [
      {
        id: "wed-b1",
        name: "Ogi & Honeycomb",
        description:
          "Fermented corn porridge with raw honeycomb and tiger nuts",
        price: 1800,
        calories: 260,
        protein: 6,
        carbs: 55,
        fat: 5,
        fiber: 7,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Probiotic", "Digestive Aid", "Energy Boost"],
        conditions: ["diabetes", "liver"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Fermented Corn",
          "Raw Honeycomb",
          "Tiger Nuts",
          "Dates",
        ],
        healthImpact:
          "Fermented ogi introduces probiotics that improve gut microbiome diversity.",
      },
      {
        id: "wed-l1",
        name: "Efo Riro & Brown Rice",
        description:
          "Yoruba spinach stew with locust beans and smoked fish",
        price: 4200,
        calories: 420,
        protein: 26,
        carbs: 55,
        fat: 15,
        fiber: 13,
        glycemicIndex: "Low",
        sodiumLevel: "Medium",
        tags: ["High Fiber", "Iron Rich", "Anti-Inflammatory"],
        conditions: ["weightloss", "liver", "hypertension"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Organic Spinach",
          "Iru (Locust Beans)",
          "Smoked Fish",
          "Palm Oil",
        ],
        healthImpact:
          "One of the most nutrient-dense Nigerian dishes, rich in iron, vitamins A, C and K.",
      },
      {
        id: "wed-d1",
        name: "Baked Catfish & Plantain",
        description:
          "Herb-baked catfish with grilled unripe plantain and pepper salsa",
        price: 5800,
        calories: 500,
        protein: 42,
        carbs: 44,
        fat: 16,
        fiber: 8,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Protein Rich", "Heart Healthy", "Gluten-Free"],
        conditions: ["hypertension", "weightloss", "diabetes"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: [
          "Wild Catfish",
          "Unripe Plantain",
          "Uziza",
          "Fresh Tomatoes",
        ],
        healthImpact:
          "Unripe plantain has a lower glycaemic index than ripe and is rich in resistant starch.",
      },
      {
        id: "wed-dr1",
        name: "Soursop Leaf Tea",
        description: "Hand-picked soursop leaves, slow-steeped and chilled",
        price: 1500,
        calories: 15,
        protein: 0,
        carbs: 3,
        fat: 0,
        fiber: 0,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Anti-Inflammatory", "Detox", "Immune Boost"],
        conditions: ["liver", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Soursop Leaves", "Water", "Lemon"],
        healthImpact:
          "Traditional West African remedy known for anti-inflammatory and immune-supporting properties.",
      },
      {
        id: "wed-dr2",
        name: "Bitter Leaf Detox Water",
        description: "Pressed with lemon and cucumber, naturally unsweetened",
        price: 1400,
        calories: 20,
        protein: 0,
        carbs: 4,
        fat: 0,
        fiber: 1,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Detox", "Liver Support", "Anti-Inflammatory"],
        conditions: ["liver", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Bitter Leaf", "Cucumber", "Lemon", "Mint"],
        healthImpact:
          "Bitter leaf is one of the most powerful hepatoprotective plants in Nigerian pharmacopeia.",
      },
    ],
  },
  {
    day: "Thursday",
    theme: "Niger Delta Feast",
    themeDescription:
      "Coastal flavors and riverine ingredients from the Delta heartland.",
    meals: [
      {
        id: "thu-b1",
        name: "Ukodo Yam Pepper Soup",
        description:
          "Traditional yam pepper soup with periwinkle and catfish",
        price: 3000,
        calories: 290,
        protein: 20,
        carbs: 38,
        fat: 8,
        fiber: 5,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Anti-Inflammatory", "Protein Rich", "Detox"],
        conditions: ["liver", "hypertension"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Yam",
          "Periwinkle",
          "Catfish",
          "Pepper Soup Spices",
        ],
        healthImpact:
          "Traditional pepper soup spices have potent anti-inflammatory and immune-boosting properties.",
      },
      {
        id: "thu-l1",
        name: "Banga Soup & Ofada Rice",
        description:
          "Palm nut cream soup with local spices and native brown rice",
        price: 5200,
        calories: 520,
        protein: 30,
        carbs: 58,
        fat: 22,
        fiber: 9,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Heart Healthy", "Antioxidant", "High Fiber"],
        conditions: ["hypertension", "weightloss"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Palm Nuts",
          "Ofada Rice",
          "Crayfish",
          "Oburunbebe Stick",
        ],
        healthImpact:
          "Ofada rice has a lower GI than regular white rice with higher fibre and micronutrient content.",
      },
      {
        id: "thu-d1",
        name: "Grilled Tilapia & Yam",
        description:
          "Whole tilapia grilled with purple yam wedges and garden egg salsa",
        price: 6500,
        calories: 550,
        protein: 45,
        carbs: 50,
        fat: 18,
        fiber: 8,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Protein Rich", "Heart Healthy", "Keto"],
        conditions: ["weightloss", "diabetes", "hypertension"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: [
          "Wild Tilapia",
          "Purple Yam",
          "Garden Egg",
          "Scent Leaves",
        ],
        healthImpact:
          "Fresh tilapia is a lean protein source rich in phosphorus supporting bone mineral density.",
      },
      {
        id: "thu-dr1",
        name: "Palm Wine Alternative",
        description: "Fermented tiger nut drink with spices, 0% alcohol",
        price: 1600,
        calories: 80,
        protein: 2,
        carbs: 18,
        fat: 2,
        fiber: 3,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Probiotic", "Digestive Aid"],
        conditions: ["liver", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Tiger Nuts", "Fermented Sorghum", "Spices"],
        healthImpact:
          "Non-alcoholic probiotic-rich drink mirroring the cultural experience of palm wine.",
      },
      {
        id: "thu-dr2",
        name: "Coconut Water Infusion",
        description: "Fresh coconut water with mint and lime",
        price: 1400,
        calories: 45,
        protein: 0,
        carbs: 11,
        fat: 0,
        fiber: 0,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Electrolytes", "Immune Boost", "Heart Healthy"],
        conditions: ["hypertension", "weightloss", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Fresh Coconut", "Mint", "Lime"],
        healthImpact:
          "Natural electrolytes replenish potassium which counteracts sodium's blood pressure effects.",
      },
    ],
  },
  {
    day: "Friday",
    theme: "Lagos Fusion",
    themeDescription:
      "Contemporary Nigerian flavors meeting global wellness trends, city-style.",
    meals: [
      {
        id: "fri-b1",
        name: "Avocado on Agege",
        description:
          "Smashed avocado on artisan Agege bread with egg and garden herbs",
        price: 3500,
        calories: 380,
        protein: 16,
        carbs: 42,
        fat: 18,
        fiber: 9,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Heart Healthy", "High Fiber", "Protein Rich"],
        conditions: ["hypertension", "weightloss"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Hass Avocado",
          "Agege Bread",
          "Egg",
          "Scent Leaves",
        ],
        healthImpact:
          "Avocado's monounsaturated fats actively reduce LDL cholesterol and support heart health.",
      },
      {
        id: "fri-l1",
        name: "Ugu & Quinoa Power Bowl",
        description: "Extra grilled chicken, no garlic",
        price: 4500,
        calories: 450,
        protein: 36,
        carbs: 48,
        fat: 14,
        fiber: 11,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["High Protein", "High Fiber", "Keto"],
        conditions: ["weightloss", "diabetes"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Quinoa",
          "Ugu Leaves",
          "Grilled Chicken",
          "Lemon Dressing",
        ],
        healthImpact:
          "Complete protein from quinoa combined with iron-rich ugu supports muscle recovery and energy.",
      },
      {
        id: "fri-d1",
        name: "Grilled Herb Croaker",
        description: "With roasted plantain and garlic herb sauce",
        price: 6200,
        calories: 520,
        protein: 40,
        carbs: 46,
        fat: 18,
        fiber: 7,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Protein Rich", "Gluten-Free", "Heart Healthy"],
        conditions: ["hypertension", "weightloss"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: [
          "Wild Croaker",
          "Plantain",
          "Garlic",
          "Fresh Herbs",
        ],
        healthImpact:
          "Wild-caught fish provides omega-3 EPA and DHA essential for reducing cardiac inflammation.",
      },
      {
        id: "fri-dr1",
        name: "Cold-Pressed Zobo",
        description: "Cold pressed hibiscus, unsweetened",
        price: 1800,
        calories: 40,
        protein: 0,
        carbs: 10,
        fat: 0,
        fiber: 1,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Antioxidant", "Heart Healthy"],
        conditions: ["hypertension", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Hibiscus", "Ginger", "Clove"],
        healthImpact:
          "Clinical studies show hibiscus tea reduces systolic blood pressure significantly.",
      },
      {
        id: "fri-dr2",
        name: "Ginger-Pineapple Blend",
        description: "Fresh pressed with black pepper for bioavailability",
        price: 1500,
        calories: 70,
        protein: 0,
        carbs: 17,
        fat: 0,
        fiber: 1,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Digestive Aid", "Anti-Inflammatory", "Energy Boost"],
        conditions: ["liver", "weightloss"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: [
          "Fresh Pineapple",
          "Ginger",
          "Black Pepper",
          "Lime",
        ],
        healthImpact:
          "Bromelain in pineapple reduces inflammation while ginger aids protein digestion.",
      },
    ],
  },
  {
    day: "Saturday",
    theme: "Yoruba Heritage",
    themeDescription:
      "Timeless Yoruba traditions, each dish carrying the wisdom of generations.",
    meals: [
      {
        id: "sat-b1",
        name: "Ekuru & Stew",
        description:
          "Steamed white bean pudding with palm oil stew and smoked fish",
        price: 2500,
        calories: 310,
        protein: 19,
        carbs: 40,
        fat: 10,
        fiber: 10,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Protein Rich", "High Fiber", "Low Sodium"],
        conditions: ["diabetes", "hypertension", "weightloss"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Black-eyed Beans",
          "Palm Oil",
          "Smoked Fish",
          "Locust Beans",
        ],
        healthImpact:
          "Bean-based protein with resistant starch supports slow glucose release and gut health.",
      },
      {
        id: "sat-l1",
        name: "Gbegiri & Amala",
        description: "Creamy bean soup with yam flour swallow and stew",
        price: 4000,
        calories: 480,
        protein: 22,
        carbs: 72,
        fat: 12,
        fiber: 12,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["High Fiber", "Protein Rich", "Iron Rich"],
        conditions: ["weightloss", "liver"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Brown Beans",
          "Yam Flour",
          "Scent Leaves",
          "Crayfish",
        ],
        healthImpact:
          "Amala from yam flour is rich in potassium and supports blood pressure regulation.",
      },
      {
        id: "sat-d1",
        name: "Asaro & Fried Plantain",
        description: "Spiced yam porridge with palm oil and fried plantain",
        price: 5000,
        calories: 460,
        protein: 12,
        carbs: 82,
        fat: 14,
        fiber: 9,
        glycemicIndex: "Medium",
        sodiumLevel: "Low",
        tags: ["Gluten-Free", "High Fiber", "Comfort Food"],
        conditions: ["liver", "hypertension"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: ["Yam", "Palm Oil", "Plantain", "Iru"],
        healthImpact:
          "Yam is rich in complex carbohydrates and provides steady energy release through the night.",
      },
      {
        id: "sat-dr1",
        name: "Kunu Aya",
        description: "Tiger nut milk, lightly spiced with date and ginger",
        price: 1500,
        calories: 90,
        protein: 2,
        carbs: 20,
        fat: 3,
        fiber: 4,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Dairy-Free", "Probiotic", "Energy Boost"],
        conditions: ["allergies", "diabetes", "liver"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Tiger Nuts", "Dates", "Ginger", "Clove"],
        healthImpact:
          "Tiger nuts are a prebiotic powerhouse, feeding beneficial gut bacteria.",
      },
      {
        id: "sat-dr2",
        name: "Aloe Vera Refresher",
        description: "Fresh aloe gel with cucumber and lemon",
        price: 1600,
        calories: 25,
        protein: 0,
        carbs: 6,
        fat: 0,
        fiber: 0,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Detox", "Liver Support", "Anti-Inflammatory"],
        conditions: ["liver", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Aloe Vera", "Cucumber", "Lemon", "Mint"],
        healthImpact:
          "Aloe vera contains acemannan which supports immune function and liver detoxification.",
      },
    ],
  },
  {
    day: "Sunday",
    theme: "Cross River Specials",
    themeDescription:
      "Rare Cross River culinary heritage, celebrating biodiversity and ancestral wisdom.",
    meals: [
      {
        id: "sun-b1",
        name: "Ekpang Nkukwo",
        description:
          "Grated cocoyam and waterleaf wrapped in cocoyam leaves, slow-cooked",
        price: 3200,
        calories: 340,
        protein: 14,
        carbs: 55,
        fat: 10,
        fiber: 11,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["High Fiber", "Gluten-Free", "Iron Rich"],
        conditions: ["diabetes", "weightloss", "liver"],
        mealType: "breakfast",
        image: require("@/assets/images/meal-akara.png"),
        healingIngredients: [
          "Cocoyam",
          "Waterleaf",
          "Periwinkle",
          "Palm Oil",
        ],
        healthImpact:
          "Cocoyam has significantly lower GI than regular yam, supporting diabetic management.",
      },
      {
        id: "sun-l1",
        name: "Afang Soup & Pounded Yam",
        description:
          "Wild Afang forest leaves with waterleaf and assorted seafood",
        price: 5500,
        calories: 530,
        protein: 32,
        carbs: 60,
        fat: 20,
        fiber: 14,
        glycemicIndex: "Medium",
        sodiumLevel: "Medium",
        tags: ["Iron Rich", "Protein Rich", "Anti-Inflammatory"],
        conditions: ["liver", "weightloss"],
        mealType: "lunch",
        image: require("@/assets/images/meal-egusi.png"),
        healingIngredients: [
          "Afang Leaves",
          "Waterleaf",
          "Periwinkle",
          "Palm Oil",
        ],
        healthImpact:
          "Afang leaves are among the highest in minerals of any West African vegetable.",
      },
      {
        id: "sun-d1",
        name: "Oha & Plantain Porridge",
        description:
          "Heritage Nigerian powerhouse with dry fish and oha leaves",
        price: 5800,
        calories: 480,
        protein: 28,
        carbs: 62,
        fat: 14,
        fiber: 12,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["High Fiber", "Anti-Inflammatory", "Low Glycemic"],
        conditions: ["diabetes", "hypertension", "liver"],
        mealType: "dinner",
        image: require("@/assets/images/meal-tilapia.png"),
        healingIngredients: [
          "Oha Leaves",
          "Unripe Plantain",
          "Dry Fish",
          "Uziza",
        ],
        healthImpact:
          "Unripe plantain provides resistant starch rich in potassium and anti-inflammatory compounds.",
      },
      {
        id: "sun-dr1",
        name: "Prekese Tea",
        description:
          "Tetrapleura tetraptera pod brew, lightly sweetened with dates",
        price: 1600,
        calories: 30,
        protein: 0,
        carbs: 7,
        fat: 0,
        fiber: 1,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Anti-Inflammatory", "Heart Healthy", "Immune Boost"],
        conditions: ["hypertension", "liver", "diabetes"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Prekese Pods", "Clove", "Ginger", "Dates"],
        healthImpact:
          "Prekese is rich in tannins and flavonoids with documented antihypertensive properties.",
      },
      {
        id: "sun-dr2",
        name: "African Star Apple Juice",
        description: "Agbalumo pressed fresh, naturally sweet and tart",
        price: 1700,
        calories: 60,
        protein: 1,
        carbs: 14,
        fat: 0,
        fiber: 3,
        glycemicIndex: "Low",
        sodiumLevel: "Low",
        tags: ["Vitamin C", "Antioxidant", "Digestive Aid"],
        conditions: ["diabetes", "liver", "weightloss"],
        mealType: "drink",
        image: require("@/assets/images/drink-zobo.png"),
        healingIngredients: ["Agbalumo (African Star Apple)"],
        healthImpact:
          "One of the richest sources of Vitamin C in West Africa with natural blood sugar regulation.",
      },
    ],
  },
];

export function getTodayMenu(): DayMenu {
  const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  const today = days[new Date().getDay()];
  return WEEKLY_MENU.find((d) => d.day === today) ?? WEEKLY_MENU[0];
}

export function getTomorrowMenu(): DayMenu {
  const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  const tomorrow = days[(new Date().getDay() + 1) % 7];
  return WEEKLY_MENU.find((d) => d.day === tomorrow) ?? WEEKLY_MENU[1];
}

export function getMealById(id: string): Meal | undefined {
  for (const day of WEEKLY_MENU) {
    const meal = day.meals.find((m) => m.id === id);
    if (meal) return meal;
  }
  return undefined;
}

export function filterMealsForConditions(
  meals: Meal[],
  conditions: Condition[]
): Meal[] {
  if (conditions.length === 0) return meals;
  return meals.filter(
    (m) =>
      m.mealType !== "drink" &&
      conditions.some((c) => m.conditions.includes(c))
  );
}

export { WEEKLY_MENU };
